# Generated by Django 3.0.7 on 2020-10-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('team_pic', models.CharField(default='images/default.png', max_length=128)),
                ('date', models.DateTimeField(null=True)),
                ('position', models.CharField(max_length=128, null=True)),
                ('head_cocah', models.CharField(max_length=128, null=True)),
                ('aarea', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('sex', models.CharField(default='男', max_length=32)),
                ('userpic', models.CharField(default='images/default.png', max_length=128)),
                ('date', models.DateTimeField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('palace', models.CharField(max_length=128, null=True)),
                ('rights', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=64, null=True)),
                ('team_id', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
