# Generated by Django 3.0.7 on 2020-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_one', models.IntegerField()),
                ('team_two', models.IntegerField()),
                ('time', models.DateTimeField(null=True)),
                ('home', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
