# Generated by Django 3.0.7 on 2020-10-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
