# Generated by Django 3.0.7 on 2020-10-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_player_basic_where_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiXun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('boss_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
            ],
        ),
    ]
