# Generated by Django 3.0.7 on 2020-10-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_jixun'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('body_fat', models.FloatField(null=True)),
                ('s_reach', models.FloatField(null=True)),
                ('wingspan', models.FloatField(null=True)),
                ('b_press', models.FloatField(null=True)),
                ('s_run', models.FloatField(null=True)),
                ('b_run', models.FloatField(null=True)),
                ('f_basket', models.FloatField(null=True)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
    ]
