# Generated by Django 3.0.7 on 2020-11-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_player_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('money', models.IntegerField()),
                ('jiaoyi', models.CharField(max_length=32)),
                ('p_chance', models.CharField(max_length=32)),
                ('p_year', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
