# Generated by Django 3.0.7 on 2020-11-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201109_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
