# Generated by Django 3.1.3 on 2020-11-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_signup_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tactics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('start_player', models.CharField(max_length=64)),
                ('end_player', models.CharField(max_length=64)),
                ('main_player', models.CharField(max_length=64)),
                ('context', models.CharField(max_length=128, null=True)),
                ('file', models.CharField(max_length=64, null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('create_user', models.CharField(max_length=32)),
                ('update_uer', models.CharField(max_length=32)),
                ('team_id', models.IntegerField(null=True)),
            ],
        ),
    ]
